/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module CDC(Reset, V_LOW, V_HIGH, V_GND, V_SENSE, Conversion_Finished);
  wire \CAP_CHAIN.I ;
  wire \CAP_CHAIN.O ;
  wire \CAP_CHAIN.cap_chain1 ;
  wire \CAP_CHAIN.cap_chain10 ;
  wire \CAP_CHAIN.cap_chain11 ;
  wire \CAP_CHAIN.cap_chain12 ;
  wire \CAP_CHAIN.cap_chain13 ;
  wire \CAP_CHAIN.cap_chain14 ;
  wire \CAP_CHAIN.cap_chain15 ;
  wire \CAP_CHAIN.cap_chain2 ;
  wire \CAP_CHAIN.cap_chain3 ;
  wire \CAP_CHAIN.cap_chain4 ;
  wire \CAP_CHAIN.cap_chain5 ;
  wire \CAP_CHAIN.cap_chain6 ;
  wire \CAP_CHAIN.cap_chain7 ;
  wire \CAP_CHAIN.cap_chain8 ;
  wire \CAP_CHAIN.cap_chain9 ;
  wire \CAP_CHAIN.cap_chain_inv1.I ;
  wire \CAP_CHAIN.cap_chain_inv1.O ;
  wire \CAP_CHAIN.cap_chain_inv10.I ;
  wire \CAP_CHAIN.cap_chain_inv10.O ;
  wire \CAP_CHAIN.cap_chain_inv11.I ;
  wire \CAP_CHAIN.cap_chain_inv11.O ;
  wire \CAP_CHAIN.cap_chain_inv12.I ;
  wire \CAP_CHAIN.cap_chain_inv12.O ;
  wire \CAP_CHAIN.cap_chain_inv13.I ;
  wire \CAP_CHAIN.cap_chain_inv13.O ;
  wire \CAP_CHAIN.cap_chain_inv14.I ;
  wire \CAP_CHAIN.cap_chain_inv14.O ;
  wire \CAP_CHAIN.cap_chain_inv15.I ;
  wire \CAP_CHAIN.cap_chain_inv15.O ;
  wire \CAP_CHAIN.cap_chain_inv16.I ;
  wire \CAP_CHAIN.cap_chain_inv16.O ;
  wire \CAP_CHAIN.cap_chain_inv2.I ;
  wire \CAP_CHAIN.cap_chain_inv2.O ;
  wire \CAP_CHAIN.cap_chain_inv3.I ;
  wire \CAP_CHAIN.cap_chain_inv3.O ;
  wire \CAP_CHAIN.cap_chain_inv4.I ;
  wire \CAP_CHAIN.cap_chain_inv4.O ;
  wire \CAP_CHAIN.cap_chain_inv5.I ;
  wire \CAP_CHAIN.cap_chain_inv5.O ;
  wire \CAP_CHAIN.cap_chain_inv6.I ;
  wire \CAP_CHAIN.cap_chain_inv6.O ;
  wire \CAP_CHAIN.cap_chain_inv7.I ;
  wire \CAP_CHAIN.cap_chain_inv7.O ;
  wire \CAP_CHAIN.cap_chain_inv8.I ;
  wire \CAP_CHAIN.cap_chain_inv8.O ;
  wire \CAP_CHAIN.cap_chain_inv9.I ;
  wire \CAP_CHAIN.cap_chain_inv9.O ;
  wire \CLOCK_GEN.CLKb ;
  wire \CLOCK_GEN.Conv_Finish ;
  wire \CLOCK_GEN.Done_Falling ;
  wire \CLOCK_GEN.Done_Rising ;
  wire \CLOCK_GEN.Finish ;
  wire \CLOCK_GEN.FinishB_Delay ;
  wire \CLOCK_GEN.Finish_Delay ;
  wire \CLOCK_GEN.INV_F.I ;
  wire \CLOCK_GEN.INV_F.O ;
  wire \CLOCK_GEN.INV_OE.I ;
  wire \CLOCK_GEN.INV_OE.O ;
  wire \CLOCK_GEN.INV_R.I ;
  wire \CLOCK_GEN.INV_R.O ;
  wire \CLOCK_GEN.NAND_CLK.A ;
  wire \CLOCK_GEN.NAND_CLK.B ;
  wire \CLOCK_GEN.NAND_CLK.O ;
  wire \CLOCK_GEN.NAND_DF.A ;
  wire \CLOCK_GEN.NAND_DF.B ;
  wire \CLOCK_GEN.NAND_DF.O ;
  wire \CLOCK_GEN.NAND_DR.A ;
  wire \CLOCK_GEN.NAND_DR.B ;
  wire \CLOCK_GEN.NAND_DR.O ;
  wire \CLOCK_GEN.NOR_CLK.A ;
  wire \CLOCK_GEN.NOR_CLK.B ;
  wire \CLOCK_GEN.NOR_CLK.O ;
  wire \CLOCK_GEN.NOT_CLK.I ;
  wire \CLOCK_GEN.NOT_CLK.O ;
  wire \CLOCK_GEN.Next_Edge ;
  wire \CLOCK_GEN.OE_Falling ;
  wire \CLOCK_GEN.OE_Rising ;
  wire \CLOCK_GEN.Reset ;
  wire \CLOCK_GEN.ResetB ;
  wire \CLOCK_GEN.Reset_OE ;
  wire \CLOCK_GEN.SR_OE.NANDQ.A ;
  wire \CLOCK_GEN.SR_OE.NANDQ.B ;
  wire \CLOCK_GEN.SR_OE.NANDQ.O ;
  wire \CLOCK_GEN.SR_OE.NANDQb.A ;
  wire \CLOCK_GEN.SR_OE.NANDQb.B ;
  wire \CLOCK_GEN.SR_OE.NANDQb.O ;
  wire \CLOCK_GEN.SR_OE.Q ;
  wire \CLOCK_GEN.SR_OE.Qb ;
  wire \CLOCK_GEN.SR_OE.Rb ;
  wire \CLOCK_GEN.SR_OE.Sb ;
  wire \CLOCK_GEN.SR_Op.NANDQ.A ;
  wire \CLOCK_GEN.SR_Op.NANDQ.B ;
  wire \CLOCK_GEN.SR_Op.NANDQ.O ;
  wire \CLOCK_GEN.SR_Op.NANDQb.A ;
  wire \CLOCK_GEN.SR_Op.NANDQb.B ;
  wire \CLOCK_GEN.SR_Op.NANDQb.O ;
  wire \CLOCK_GEN.SR_Op.Q ;
  wire \CLOCK_GEN.SR_Op.Qb ;
  wire \CLOCK_GEN.SR_Op.Rb ;
  wire \CLOCK_GEN.SR_Op.Sb ;
  wire \CLOCK_GEN.Sense ;
  wire \CLOCK_GEN.Set_OE ;
  output Conversion_Finished;
  wire \FALLING_COMP.D_Minus ;
  wire \FALLING_COMP.D_Plus ;
  wire \FALLING_COMP.Db_Minus ;
  wire \FALLING_COMP.Db_Plus ;
  wire \FALLING_COMP.Done ;
  wire \FALLING_COMP.INV_DM.I ;
  wire \FALLING_COMP.INV_DM.O ;
  wire \FALLING_COMP.INV_DP.I ;
  wire \FALLING_COMP.INV_DP.O ;
  wire \FALLING_COMP.INV_Q.I ;
  wire \FALLING_COMP.INV_Q.O ;
  wire \FALLING_COMP.INV_Qb.I ;
  wire \FALLING_COMP.INV_Qb.O ;
  wire \FALLING_COMP.NAND2_COMP.A ;
  wire \FALLING_COMP.NAND2_COMP.B ;
  wire \FALLING_COMP.NAND2_COMP.O ;
  wire \FALLING_COMP.NAND3_COMP.A ;
  wire \FALLING_COMP.NAND3_COMP.B ;
  wire \FALLING_COMP.NAND3_COMP.C ;
  wire \FALLING_COMP.NAND3_COMP.O ;
  wire \FALLING_COMP.Output_Enable ;
  wire \FALLING_COMP.Q ;
  wire \FALLING_COMP.Q_b ;
  wire \FALLING_COMP.Qb ;
  wire \FALLING_COMP.Qb_b ;
  wire \FALLING_COMP.SR_MEM.NANDQ.A ;
  wire \FALLING_COMP.SR_MEM.NANDQ.B ;
  wire \FALLING_COMP.SR_MEM.NANDQ.O ;
  wire \FALLING_COMP.SR_MEM.NANDQb.A ;
  wire \FALLING_COMP.SR_MEM.NANDQb.B ;
  wire \FALLING_COMP.SR_MEM.NANDQb.O ;
  wire \FALLING_COMP.SR_MEM.Q ;
  wire \FALLING_COMP.SR_MEM.Qb ;
  wire \FALLING_COMP.SR_MEM.Rb ;
  wire \FALLING_COMP.SR_MEM.Sb ;
  wire \FALLING_COMP.Y ;
  wire \FINISH_CHAIN.I ;
  wire \FINISH_CHAIN.O ;
  wire \FINISH_CHAIN.Ob ;
  wire \FINISH_CHAIN.finish_chain1 ;
  wire \FINISH_CHAIN.finish_chain10 ;
  wire \FINISH_CHAIN.finish_chain11 ;
  wire \FINISH_CHAIN.finish_chain12 ;
  wire \FINISH_CHAIN.finish_chain13 ;
  wire \FINISH_CHAIN.finish_chain14 ;
  wire \FINISH_CHAIN.finish_chain2 ;
  wire \FINISH_CHAIN.finish_chain3 ;
  wire \FINISH_CHAIN.finish_chain4 ;
  wire \FINISH_CHAIN.finish_chain5 ;
  wire \FINISH_CHAIN.finish_chain6 ;
  wire \FINISH_CHAIN.finish_chain7 ;
  wire \FINISH_CHAIN.finish_chain8 ;
  wire \FINISH_CHAIN.finish_chain9 ;
  wire \FINISH_CHAIN.finish_chain_inv1.I ;
  wire \FINISH_CHAIN.finish_chain_inv1.O ;
  wire \FINISH_CHAIN.finish_chain_inv10.I ;
  wire \FINISH_CHAIN.finish_chain_inv10.O ;
  wire \FINISH_CHAIN.finish_chain_inv11.I ;
  wire \FINISH_CHAIN.finish_chain_inv11.O ;
  wire \FINISH_CHAIN.finish_chain_inv12.I ;
  wire \FINISH_CHAIN.finish_chain_inv12.O ;
  wire \FINISH_CHAIN.finish_chain_inv13.I ;
  wire \FINISH_CHAIN.finish_chain_inv13.O ;
  wire \FINISH_CHAIN.finish_chain_inv14.I ;
  wire \FINISH_CHAIN.finish_chain_inv14.O ;
  wire \FINISH_CHAIN.finish_chain_inv15.I ;
  wire \FINISH_CHAIN.finish_chain_inv15.O ;
  wire \FINISH_CHAIN.finish_chain_inv16.I ;
  wire \FINISH_CHAIN.finish_chain_inv16.O ;
  wire \FINISH_CHAIN.finish_chain_inv2.I ;
  wire \FINISH_CHAIN.finish_chain_inv2.O ;
  wire \FINISH_CHAIN.finish_chain_inv3.I ;
  wire \FINISH_CHAIN.finish_chain_inv3.O ;
  wire \FINISH_CHAIN.finish_chain_inv4.I ;
  wire \FINISH_CHAIN.finish_chain_inv4.O ;
  wire \FINISH_CHAIN.finish_chain_inv5.I ;
  wire \FINISH_CHAIN.finish_chain_inv5.O ;
  wire \FINISH_CHAIN.finish_chain_inv6.I ;
  wire \FINISH_CHAIN.finish_chain_inv6.O ;
  wire \FINISH_CHAIN.finish_chain_inv7.I ;
  wire \FINISH_CHAIN.finish_chain_inv7.O ;
  wire \FINISH_CHAIN.finish_chain_inv8.I ;
  wire \FINISH_CHAIN.finish_chain_inv8.O ;
  wire \FINISH_CHAIN.finish_chain_inv9.I ;
  wire \FINISH_CHAIN.finish_chain_inv9.O ;
  wire \FINISH_COMP.D_Minus ;
  wire \FINISH_COMP.D_Plus ;
  wire \FINISH_COMP.Db_Minus ;
  wire \FINISH_COMP.Db_Plus ;
  wire \FINISH_COMP.Done ;
  wire \FINISH_COMP.INV_DM.I ;
  wire \FINISH_COMP.INV_DM.O ;
  wire \FINISH_COMP.INV_DP.I ;
  wire \FINISH_COMP.INV_DP.O ;
  wire \FINISH_COMP.INV_Q.I ;
  wire \FINISH_COMP.INV_Q.O ;
  wire \FINISH_COMP.INV_Qb.I ;
  wire \FINISH_COMP.INV_Qb.O ;
  wire \FINISH_COMP.NAND2_COMP.A ;
  wire \FINISH_COMP.NAND2_COMP.B ;
  wire \FINISH_COMP.NAND2_COMP.O ;
  wire \FINISH_COMP.NAND3_COMP.A ;
  wire \FINISH_COMP.NAND3_COMP.B ;
  wire \FINISH_COMP.NAND3_COMP.C ;
  wire \FINISH_COMP.NAND3_COMP.O ;
  wire \FINISH_COMP.Output_Enable ;
  wire \FINISH_COMP.Q ;
  wire \FINISH_COMP.Q_b ;
  wire \FINISH_COMP.Qb ;
  wire \FINISH_COMP.Qb_b ;
  wire \FINISH_COMP.SR_MEM.NANDQ.A ;
  wire \FINISH_COMP.SR_MEM.NANDQ.B ;
  wire \FINISH_COMP.SR_MEM.NANDQ.O ;
  wire \FINISH_COMP.SR_MEM.NANDQb.A ;
  wire \FINISH_COMP.SR_MEM.NANDQb.B ;
  wire \FINISH_COMP.SR_MEM.NANDQb.O ;
  wire \FINISH_COMP.SR_MEM.Q ;
  wire \FINISH_COMP.SR_MEM.Qb ;
  wire \FINISH_COMP.SR_MEM.Rb ;
  wire \FINISH_COMP.SR_MEM.Sb ;
  wire \FINISH_COMP.Y ;
  wire Falling_Cap;
  wire Falling_Done;
  wire Falling_Low;
  wire Falling_Output_Enable;
  wire Falling_Y;
  wire Finish;
  wire Finish_Delay;
  wire Finish_Low;
  wire \INV_EDGE.I ;
  wire \INV_EDGE.O ;
  wire \INV_RISING_CAP.I ;
  wire \INV_RISING_CAP.O ;
  wire \INV_RISING_LOW.I ;
  wire \INV_RISING_LOW.O ;
  wire \LOW_CHAIN.I ;
  wire \LOW_CHAIN.O ;
  wire \LOW_CHAIN.low_chain1 ;
  wire \LOW_CHAIN.low_chain10 ;
  wire \LOW_CHAIN.low_chain11 ;
  wire \LOW_CHAIN.low_chain12 ;
  wire \LOW_CHAIN.low_chain13 ;
  wire \LOW_CHAIN.low_chain14 ;
  wire \LOW_CHAIN.low_chain15 ;
  wire \LOW_CHAIN.low_chain2 ;
  wire \LOW_CHAIN.low_chain3 ;
  wire \LOW_CHAIN.low_chain4 ;
  wire \LOW_CHAIN.low_chain5 ;
  wire \LOW_CHAIN.low_chain6 ;
  wire \LOW_CHAIN.low_chain7 ;
  wire \LOW_CHAIN.low_chain8 ;
  wire \LOW_CHAIN.low_chain9 ;
  wire \LOW_CHAIN.low_chain_inv1.I ;
  wire \LOW_CHAIN.low_chain_inv1.O ;
  wire \LOW_CHAIN.low_chain_inv10.I ;
  wire \LOW_CHAIN.low_chain_inv10.O ;
  wire \LOW_CHAIN.low_chain_inv11.I ;
  wire \LOW_CHAIN.low_chain_inv11.O ;
  wire \LOW_CHAIN.low_chain_inv12.I ;
  wire \LOW_CHAIN.low_chain_inv12.O ;
  wire \LOW_CHAIN.low_chain_inv13.I ;
  wire \LOW_CHAIN.low_chain_inv13.O ;
  wire \LOW_CHAIN.low_chain_inv14.I ;
  wire \LOW_CHAIN.low_chain_inv14.O ;
  wire \LOW_CHAIN.low_chain_inv15.I ;
  wire \LOW_CHAIN.low_chain_inv15.O ;
  wire \LOW_CHAIN.low_chain_inv16.I ;
  wire \LOW_CHAIN.low_chain_inv16.O ;
  wire \LOW_CHAIN.low_chain_inv2.I ;
  wire \LOW_CHAIN.low_chain_inv2.O ;
  wire \LOW_CHAIN.low_chain_inv3.I ;
  wire \LOW_CHAIN.low_chain_inv3.O ;
  wire \LOW_CHAIN.low_chain_inv4.I ;
  wire \LOW_CHAIN.low_chain_inv4.O ;
  wire \LOW_CHAIN.low_chain_inv5.I ;
  wire \LOW_CHAIN.low_chain_inv5.O ;
  wire \LOW_CHAIN.low_chain_inv6.I ;
  wire \LOW_CHAIN.low_chain_inv6.O ;
  wire \LOW_CHAIN.low_chain_inv7.I ;
  wire \LOW_CHAIN.low_chain_inv7.O ;
  wire \LOW_CHAIN.low_chain_inv8.I ;
  wire \LOW_CHAIN.low_chain_inv8.O ;
  wire \LOW_CHAIN.low_chain_inv9.I ;
  wire \LOW_CHAIN.low_chain_inv9.O ;
  wire Next_Edge_HighV;
  wire Next_Edge_LowV;
  wire Next_Edge_LowV_b;
  wire \RISING_COMP.D_Minus ;
  wire \RISING_COMP.D_Plus ;
  wire \RISING_COMP.Db_Minus ;
  wire \RISING_COMP.Db_Plus ;
  wire \RISING_COMP.Done ;
  wire \RISING_COMP.INV_DM.I ;
  wire \RISING_COMP.INV_DM.O ;
  wire \RISING_COMP.INV_DP.I ;
  wire \RISING_COMP.INV_DP.O ;
  wire \RISING_COMP.INV_Q.I ;
  wire \RISING_COMP.INV_Q.O ;
  wire \RISING_COMP.INV_Qb.I ;
  wire \RISING_COMP.INV_Qb.O ;
  wire \RISING_COMP.NAND2_COMP.A ;
  wire \RISING_COMP.NAND2_COMP.B ;
  wire \RISING_COMP.NAND2_COMP.O ;
  wire \RISING_COMP.NAND3_COMP.A ;
  wire \RISING_COMP.NAND3_COMP.B ;
  wire \RISING_COMP.NAND3_COMP.C ;
  wire \RISING_COMP.NAND3_COMP.O ;
  wire \RISING_COMP.Output_Enable ;
  wire \RISING_COMP.Q ;
  wire \RISING_COMP.Q_b ;
  wire \RISING_COMP.Qb ;
  wire \RISING_COMP.Qb_b ;
  wire \RISING_COMP.SR_MEM.NANDQ.A ;
  wire \RISING_COMP.SR_MEM.NANDQ.B ;
  wire \RISING_COMP.SR_MEM.NANDQ.O ;
  wire \RISING_COMP.SR_MEM.NANDQb.A ;
  wire \RISING_COMP.SR_MEM.NANDQb.B ;
  wire \RISING_COMP.SR_MEM.NANDQb.O ;
  wire \RISING_COMP.SR_MEM.Q ;
  wire \RISING_COMP.SR_MEM.Qb ;
  wire \RISING_COMP.SR_MEM.Rb ;
  wire \RISING_COMP.SR_MEM.Sb ;
  wire \RISING_COMP.Y ;
  input Reset;
  wire Rising_Cap;
  wire Rising_Done;
  wire Rising_Low;
  wire Rising_Output_Enable;
  wire Rising_Y;
  input V_GND;
  input V_HIGH;
  input V_LOW;
  inout V_SENSE;
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv1.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv1.I ),
    .Y(\CAP_CHAIN.cap_chain_inv1.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv10.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv10.I ),
    .Y(\CAP_CHAIN.cap_chain_inv10.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv11.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv11.I ),
    .Y(\CAP_CHAIN.cap_chain_inv11.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv12.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv12.I ),
    .Y(\CAP_CHAIN.cap_chain_inv12.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv13.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv13.I ),
    .Y(\CAP_CHAIN.cap_chain_inv13.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv14.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv14.I ),
    .Y(\CAP_CHAIN.cap_chain_inv14.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv15.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv15.I ),
    .Y(\CAP_CHAIN.cap_chain_inv15.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv16.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv16.I ),
    .Y(\CAP_CHAIN.cap_chain_inv16.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv2.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv2.I ),
    .Y(\CAP_CHAIN.cap_chain_inv2.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv3.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv3.I ),
    .Y(\CAP_CHAIN.cap_chain_inv3.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv4.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv4.I ),
    .Y(\CAP_CHAIN.cap_chain_inv4.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv5.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv5.I ),
    .Y(\CAP_CHAIN.cap_chain_inv5.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv6.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv6.I ),
    .Y(\CAP_CHAIN.cap_chain_inv6.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv7.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv7.I ),
    .Y(\CAP_CHAIN.cap_chain_inv7.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv8.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv8.I ),
    .Y(\CAP_CHAIN.cap_chain_inv8.O )
  );
  sky130_fd_sc_hd__inv_1 \CAP_CHAIN.cap_chain_inv9.cell_INV  (
    .A(\CAP_CHAIN.cap_chain_inv9.I ),
    .Y(\CAP_CHAIN.cap_chain_inv9.O )
  );
  SLC CDC_SLC (
    .IN(Next_Edge_LowV),
    .INb(Next_Edge_LowV_b),
    .VOUT(Next_Edge_HighV)
  );
  transmission_gate CDC_TRANSMISSION_GATE (
    .I(V_HIGH),
    .O(V_SENSE)
  );
  sky130_fd_sc_hd__inv_1 \CLOCK_GEN.INV_F.cell_INV  (
    .A(\CLOCK_GEN.INV_F.I ),
    .Y(\CLOCK_GEN.INV_F.O )
  );
  sky130_fd_sc_hd__inv_1 \CLOCK_GEN.INV_OE.cell_INV  (
    .A(\CLOCK_GEN.INV_OE.I ),
    .Y(\CLOCK_GEN.INV_OE.O )
  );
  sky130_fd_sc_hd__inv_1 \CLOCK_GEN.INV_R.cell_INV  (
    .A(\CLOCK_GEN.INV_R.I ),
    .Y(\CLOCK_GEN.INV_R.O )
  );
  sky130_fd_sc_hd__nand2_1 \CLOCK_GEN.NAND_CLK.cell_NAND2  (
    .A(\CLOCK_GEN.NAND_CLK.A ),
    .B(\CLOCK_GEN.NAND_CLK.B ),
    .Y(\CLOCK_GEN.NAND_CLK.O )
  );
  sky130_fd_sc_hd__nand2_1 \CLOCK_GEN.NAND_DF.cell_NAND2  (
    .A(\CLOCK_GEN.NAND_DF.A ),
    .B(\CLOCK_GEN.NAND_DF.B ),
    .Y(\CLOCK_GEN.NAND_DF.O )
  );
  sky130_fd_sc_hd__nand2_1 \CLOCK_GEN.NAND_DR.cell_NAND2  (
    .A(\CLOCK_GEN.NAND_DR.A ),
    .B(\CLOCK_GEN.NAND_DR.B ),
    .Y(\CLOCK_GEN.NAND_DR.O )
  );
  sky130_fd_sc_hd__nor2_1 \CLOCK_GEN.NOR_CLK.cell_NOR  (
    .A(\CLOCK_GEN.NOR_CLK.A ),
    .B(\CLOCK_GEN.NOR_CLK.B ),
    .Y(\CLOCK_GEN.NOR_CLK.O )
  );
  sky130_fd_sc_hd__inv_1 \CLOCK_GEN.NOT_CLK.cell_INV  (
    .A(\CLOCK_GEN.NOT_CLK.I ),
    .Y(\CLOCK_GEN.NOT_CLK.O )
  );
  sky130_fd_sc_hd__nand2_8 \CLOCK_GEN.SR_OE.NANDQ.cell_NAND2_Big  (
    .A(\CLOCK_GEN.SR_OE.NANDQ.A ),
    .B(\CLOCK_GEN.SR_OE.NANDQ.B ),
    .Y(\CLOCK_GEN.SR_OE.NANDQ.O )
  );
  sky130_fd_sc_hd__nand2_8 \CLOCK_GEN.SR_OE.NANDQb.cell_NAND2_Big  (
    .A(\CLOCK_GEN.SR_OE.NANDQb.A ),
    .B(\CLOCK_GEN.SR_OE.NANDQb.B ),
    .Y(\CLOCK_GEN.SR_OE.NANDQb.O )
  );
  sky130_fd_sc_hd__nand2_8 \CLOCK_GEN.SR_Op.NANDQ.cell_NAND2_Big  (
    .A(\CLOCK_GEN.SR_Op.NANDQ.A ),
    .B(\CLOCK_GEN.SR_Op.NANDQ.B ),
    .Y(\CLOCK_GEN.SR_Op.NANDQ.O )
  );
  sky130_fd_sc_hd__nand2_8 \CLOCK_GEN.SR_Op.NANDQb.cell_NAND2_Big  (
    .A(\CLOCK_GEN.SR_Op.NANDQb.A ),
    .B(\CLOCK_GEN.SR_Op.NANDQb.B ),
    .Y(\CLOCK_GEN.SR_Op.NANDQb.O )
  );
  sky130_fd_sc_hd__inv_1 \FALLING_COMP.INV_DM.cell_INV  (
    .A(\FALLING_COMP.INV_DM.I ),
    .Y(\FALLING_COMP.INV_DM.O )
  );
  sky130_fd_sc_hd__inv_1 \FALLING_COMP.INV_DP.cell_INV  (
    .A(\FALLING_COMP.INV_DP.I ),
    .Y(\FALLING_COMP.INV_DP.O )
  );
  sky130_fd_sc_hd__inv_1 \FALLING_COMP.INV_Q.cell_INV  (
    .A(\FALLING_COMP.INV_Q.I ),
    .Y(\FALLING_COMP.INV_Q.O )
  );
  sky130_fd_sc_hd__inv_1 \FALLING_COMP.INV_Qb.cell_INV  (
    .A(\FALLING_COMP.INV_Qb.I ),
    .Y(\FALLING_COMP.INV_Qb.O )
  );
  sky130_fd_sc_hd__nand2_1 \FALLING_COMP.NAND2_COMP.cell_NAND2  (
    .A(\FALLING_COMP.NAND2_COMP.A ),
    .B(\FALLING_COMP.NAND2_COMP.B ),
    .Y(\FALLING_COMP.NAND2_COMP.O )
  );
  sky130_fd_sc_hd__nand3_1 \FALLING_COMP.NAND3_COMP.cell_NAND3  (
    .A(\FALLING_COMP.NAND3_COMP.A ),
    .B(\FALLING_COMP.NAND3_COMP.B ),
    .C(\FALLING_COMP.NAND3_COMP.C ),
    .Y(\FALLING_COMP.NAND3_COMP.O )
  );
  sky130_fd_sc_hd__nand2_8 \FALLING_COMP.SR_MEM.NANDQ.cell_NAND2_Big  (
    .A(\FALLING_COMP.SR_MEM.NANDQ.A ),
    .B(\FALLING_COMP.SR_MEM.NANDQ.B ),
    .Y(\FALLING_COMP.SR_MEM.NANDQ.O )
  );
  sky130_fd_sc_hd__nand2_8 \FALLING_COMP.SR_MEM.NANDQb.cell_NAND2_Big  (
    .A(\FALLING_COMP.SR_MEM.NANDQb.A ),
    .B(\FALLING_COMP.SR_MEM.NANDQb.B ),
    .Y(\FALLING_COMP.SR_MEM.NANDQb.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv1.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv1.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv1.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv10.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv10.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv10.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv11.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv11.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv11.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv12.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv12.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv12.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv13.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv13.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv13.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv14.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv14.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv14.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv15.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv15.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv15.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv16.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv16.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv16.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv2.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv2.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv2.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv3.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv3.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv3.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv4.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv4.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv4.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv5.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv5.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv5.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv6.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv6.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv6.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv7.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv7.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv7.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv8.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv8.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv8.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_CHAIN.finish_chain_inv9.cell_INV  (
    .A(\FINISH_CHAIN.finish_chain_inv9.I ),
    .Y(\FINISH_CHAIN.finish_chain_inv9.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_COMP.INV_DM.cell_INV  (
    .A(\FINISH_COMP.INV_DM.I ),
    .Y(\FINISH_COMP.INV_DM.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_COMP.INV_DP.cell_INV  (
    .A(\FINISH_COMP.INV_DP.I ),
    .Y(\FINISH_COMP.INV_DP.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_COMP.INV_Q.cell_INV  (
    .A(\FINISH_COMP.INV_Q.I ),
    .Y(\FINISH_COMP.INV_Q.O )
  );
  sky130_fd_sc_hd__inv_1 \FINISH_COMP.INV_Qb.cell_INV  (
    .A(\FINISH_COMP.INV_Qb.I ),
    .Y(\FINISH_COMP.INV_Qb.O )
  );
  sky130_fd_sc_hd__nand2_1 \FINISH_COMP.NAND2_COMP.cell_NAND2  (
    .A(\FINISH_COMP.NAND2_COMP.A ),
    .B(\FINISH_COMP.NAND2_COMP.B ),
    .Y(\FINISH_COMP.NAND2_COMP.O )
  );
  sky130_fd_sc_hd__nand3_1 \FINISH_COMP.NAND3_COMP.cell_NAND3  (
    .A(\FINISH_COMP.NAND3_COMP.A ),
    .B(\FINISH_COMP.NAND3_COMP.B ),
    .C(\FINISH_COMP.NAND3_COMP.C ),
    .Y(\FINISH_COMP.NAND3_COMP.O )
  );
  sky130_fd_sc_hd__nand2_8 \FINISH_COMP.SR_MEM.NANDQ.cell_NAND2_Big  (
    .A(\FINISH_COMP.SR_MEM.NANDQ.A ),
    .B(\FINISH_COMP.SR_MEM.NANDQ.B ),
    .Y(\FINISH_COMP.SR_MEM.NANDQ.O )
  );
  sky130_fd_sc_hd__nand2_8 \FINISH_COMP.SR_MEM.NANDQb.cell_NAND2_Big  (
    .A(\FINISH_COMP.SR_MEM.NANDQb.A ),
    .B(\FINISH_COMP.SR_MEM.NANDQb.B ),
    .Y(\FINISH_COMP.SR_MEM.NANDQb.O )
  );
  sky130_fd_sc_hd__inv_1 \INV_EDGE.cell_INV  (
    .A(\INV_EDGE.I ),
    .Y(\INV_EDGE.O )
  );
  sky130_fd_sc_hd__inv_1 \INV_RISING_CAP.cell_INV  (
    .A(\INV_RISING_CAP.I ),
    .Y(\INV_RISING_CAP.O )
  );
  sky130_fd_sc_hd__inv_1 \INV_RISING_LOW.cell_INV  (
    .A(\INV_RISING_LOW.I ),
    .Y(\INV_RISING_LOW.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv1.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv1.I ),
    .Y(\LOW_CHAIN.low_chain_inv1.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv10.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv10.I ),
    .Y(\LOW_CHAIN.low_chain_inv10.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv11.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv11.I ),
    .Y(\LOW_CHAIN.low_chain_inv11.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv12.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv12.I ),
    .Y(\LOW_CHAIN.low_chain_inv12.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv13.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv13.I ),
    .Y(\LOW_CHAIN.low_chain_inv13.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv14.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv14.I ),
    .Y(\LOW_CHAIN.low_chain_inv14.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv15.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv15.I ),
    .Y(\LOW_CHAIN.low_chain_inv15.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv16.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv16.I ),
    .Y(\LOW_CHAIN.low_chain_inv16.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv2.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv2.I ),
    .Y(\LOW_CHAIN.low_chain_inv2.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv3.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv3.I ),
    .Y(\LOW_CHAIN.low_chain_inv3.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv4.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv4.I ),
    .Y(\LOW_CHAIN.low_chain_inv4.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv5.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv5.I ),
    .Y(\LOW_CHAIN.low_chain_inv5.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv6.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv6.I ),
    .Y(\LOW_CHAIN.low_chain_inv6.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv7.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv7.I ),
    .Y(\LOW_CHAIN.low_chain_inv7.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv8.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv8.I ),
    .Y(\LOW_CHAIN.low_chain_inv8.O )
  );
  sky130_fd_sc_hd__inv_1 \LOW_CHAIN.low_chain_inv9.cell_INV  (
    .A(\LOW_CHAIN.low_chain_inv9.I ),
    .Y(\LOW_CHAIN.low_chain_inv9.O )
  );
  sky130_fd_sc_hd__inv_1 \RISING_COMP.INV_DM.cell_INV  (
    .A(\RISING_COMP.INV_DM.I ),
    .Y(\RISING_COMP.INV_DM.O )
  );
  sky130_fd_sc_hd__inv_1 \RISING_COMP.INV_DP.cell_INV  (
    .A(\RISING_COMP.INV_DP.I ),
    .Y(\RISING_COMP.INV_DP.O )
  );
  sky130_fd_sc_hd__inv_1 \RISING_COMP.INV_Q.cell_INV  (
    .A(\RISING_COMP.INV_Q.I ),
    .Y(\RISING_COMP.INV_Q.O )
  );
  sky130_fd_sc_hd__inv_1 \RISING_COMP.INV_Qb.cell_INV  (
    .A(\RISING_COMP.INV_Qb.I ),
    .Y(\RISING_COMP.INV_Qb.O )
  );
  sky130_fd_sc_hd__nand2_1 \RISING_COMP.NAND2_COMP.cell_NAND2  (
    .A(\RISING_COMP.NAND2_COMP.A ),
    .B(\RISING_COMP.NAND2_COMP.B ),
    .Y(\RISING_COMP.NAND2_COMP.O )
  );
  sky130_fd_sc_hd__nand3_1 \RISING_COMP.NAND3_COMP.cell_NAND3  (
    .A(\RISING_COMP.NAND3_COMP.A ),
    .B(\RISING_COMP.NAND3_COMP.B ),
    .C(\RISING_COMP.NAND3_COMP.C ),
    .Y(\RISING_COMP.NAND3_COMP.O )
  );
  sky130_fd_sc_hd__nand2_8 \RISING_COMP.SR_MEM.NANDQ.cell_NAND2_Big  (
    .A(\RISING_COMP.SR_MEM.NANDQ.A ),
    .B(\RISING_COMP.SR_MEM.NANDQ.B ),
    .Y(\RISING_COMP.SR_MEM.NANDQ.O )
  );
  sky130_fd_sc_hd__nand2_8 \RISING_COMP.SR_MEM.NANDQb.cell_NAND2_Big  (
    .A(\RISING_COMP.SR_MEM.NANDQb.A ),
    .B(\RISING_COMP.SR_MEM.NANDQb.B ),
    .Y(\RISING_COMP.SR_MEM.NANDQb.O )
  );
  assign Falling_Low = \LOW_CHAIN.O ;
  assign \LOW_CHAIN.I  = Next_Edge_HighV;
  assign Rising_Low = \INV_RISING_LOW.O ;
  assign \INV_RISING_LOW.I  = Falling_Low;
  assign Finish_Low = \FINISH_CHAIN.O ;
  assign Finish_Delay = \FINISH_CHAIN.Ob ;
  assign \FINISH_CHAIN.I  = Rising_Low;
  assign Falling_Cap = \CAP_CHAIN.O ;
  assign \CAP_CHAIN.I  = Next_Edge_HighV;
  assign Falling_Y = \FALLING_COMP.Y ;
  assign Falling_Done = \FALLING_COMP.Done ;
  assign \FALLING_COMP.Output_Enable  = Falling_Output_Enable;
  assign \FALLING_COMP.D_Minus  = Falling_Low;
  assign \FALLING_COMP.D_Plus  = Falling_Cap;
  assign Rising_Cap = \INV_RISING_CAP.O ;
  assign \INV_RISING_CAP.I  = Falling_Cap;
  assign Rising_Y = \RISING_COMP.Y ;
  assign Rising_Done = \RISING_COMP.Done ;
  assign \RISING_COMP.Output_Enable  = Rising_Output_Enable;
  assign \RISING_COMP.D_Minus  = Rising_Low;
  assign \RISING_COMP.D_Plus  = Rising_Cap;
  assign Finish = \FINISH_COMP.Y ;
  assign \FINISH_COMP.Output_Enable  = Rising_Output_Enable;
  assign \FINISH_COMP.D_Minus  = Finish_Low;
  assign \FINISH_COMP.D_Plus  = Rising_Cap;
  assign Conversion_Finished = \CLOCK_GEN.Conv_Finish ;
  assign Next_Edge_LowV = \CLOCK_GEN.Next_Edge ;
  assign Falling_Output_Enable = \CLOCK_GEN.OE_Falling ;
  assign Rising_Output_Enable = \CLOCK_GEN.OE_Rising ;
  assign \CLOCK_GEN.Finish  = Finish;
  assign \CLOCK_GEN.Reset  = Reset;
  assign \CLOCK_GEN.Finish_Delay  = Finish_Delay;
  assign \CLOCK_GEN.Done_Falling  = Falling_Done;
  assign \CLOCK_GEN.Done_Rising  = Rising_Done;
  assign Next_Edge_LowV_b = \INV_EDGE.O ;
  assign \INV_EDGE.I  = Next_Edge_LowV;
  assign \LOW_CHAIN.low_chain1  = \LOW_CHAIN.low_chain_inv1.O ;
  assign \LOW_CHAIN.low_chain_inv1.I  = \LOW_CHAIN.I ;
  assign \LOW_CHAIN.low_chain2  = \LOW_CHAIN.low_chain_inv2.O ;
  assign \LOW_CHAIN.low_chain_inv2.I  = \LOW_CHAIN.low_chain1 ;
  assign \LOW_CHAIN.low_chain3  = \LOW_CHAIN.low_chain_inv3.O ;
  assign \LOW_CHAIN.low_chain_inv3.I  = \LOW_CHAIN.low_chain2 ;
  assign \LOW_CHAIN.low_chain4  = \LOW_CHAIN.low_chain_inv4.O ;
  assign \LOW_CHAIN.low_chain_inv4.I  = \LOW_CHAIN.low_chain3 ;
  assign \LOW_CHAIN.low_chain5  = \LOW_CHAIN.low_chain_inv5.O ;
  assign \LOW_CHAIN.low_chain_inv5.I  = \LOW_CHAIN.low_chain4 ;
  assign \LOW_CHAIN.low_chain6  = \LOW_CHAIN.low_chain_inv6.O ;
  assign \LOW_CHAIN.low_chain_inv6.I  = \LOW_CHAIN.low_chain5 ;
  assign \LOW_CHAIN.low_chain7  = \LOW_CHAIN.low_chain_inv7.O ;
  assign \LOW_CHAIN.low_chain_inv7.I  = \LOW_CHAIN.low_chain6 ;
  assign \LOW_CHAIN.low_chain8  = \LOW_CHAIN.low_chain_inv8.O ;
  assign \LOW_CHAIN.low_chain_inv8.I  = \LOW_CHAIN.low_chain7 ;
  assign \LOW_CHAIN.low_chain9  = \LOW_CHAIN.low_chain_inv9.O ;
  assign \LOW_CHAIN.low_chain_inv9.I  = \LOW_CHAIN.low_chain8 ;
  assign \LOW_CHAIN.low_chain10  = \LOW_CHAIN.low_chain_inv10.O ;
  assign \LOW_CHAIN.low_chain_inv10.I  = \LOW_CHAIN.low_chain9 ;
  assign \LOW_CHAIN.low_chain11  = \LOW_CHAIN.low_chain_inv11.O ;
  assign \LOW_CHAIN.low_chain_inv11.I  = \LOW_CHAIN.low_chain10 ;
  assign \LOW_CHAIN.low_chain12  = \LOW_CHAIN.low_chain_inv12.O ;
  assign \LOW_CHAIN.low_chain_inv12.I  = \LOW_CHAIN.low_chain11 ;
  assign \LOW_CHAIN.low_chain13  = \LOW_CHAIN.low_chain_inv13.O ;
  assign \LOW_CHAIN.low_chain_inv13.I  = \LOW_CHAIN.low_chain12 ;
  assign \LOW_CHAIN.low_chain14  = \LOW_CHAIN.low_chain_inv14.O ;
  assign \LOW_CHAIN.low_chain_inv14.I  = \LOW_CHAIN.low_chain13 ;
  assign \LOW_CHAIN.low_chain15  = \LOW_CHAIN.low_chain_inv15.O ;
  assign \LOW_CHAIN.low_chain_inv15.I  = \LOW_CHAIN.low_chain14 ;
  assign \LOW_CHAIN.O  = \LOW_CHAIN.low_chain_inv16.O ;
  assign \LOW_CHAIN.low_chain_inv16.I  = \LOW_CHAIN.low_chain15 ;
  assign \FINISH_CHAIN.finish_chain1  = \FINISH_CHAIN.finish_chain_inv1.O ;
  assign \FINISH_CHAIN.finish_chain_inv1.I  = \FINISH_CHAIN.I ;
  assign \FINISH_CHAIN.finish_chain2  = \FINISH_CHAIN.finish_chain_inv2.O ;
  assign \FINISH_CHAIN.finish_chain_inv2.I  = \FINISH_CHAIN.finish_chain1 ;
  assign \FINISH_CHAIN.finish_chain3  = \FINISH_CHAIN.finish_chain_inv3.O ;
  assign \FINISH_CHAIN.finish_chain_inv3.I  = \FINISH_CHAIN.finish_chain2 ;
  assign \FINISH_CHAIN.finish_chain4  = \FINISH_CHAIN.finish_chain_inv4.O ;
  assign \FINISH_CHAIN.finish_chain_inv4.I  = \FINISH_CHAIN.finish_chain3 ;
  assign \FINISH_CHAIN.finish_chain5  = \FINISH_CHAIN.finish_chain_inv5.O ;
  assign \FINISH_CHAIN.finish_chain_inv5.I  = \FINISH_CHAIN.finish_chain4 ;
  assign \FINISH_CHAIN.finish_chain6  = \FINISH_CHAIN.finish_chain_inv6.O ;
  assign \FINISH_CHAIN.finish_chain_inv6.I  = \FINISH_CHAIN.finish_chain5 ;
  assign \FINISH_CHAIN.finish_chain7  = \FINISH_CHAIN.finish_chain_inv7.O ;
  assign \FINISH_CHAIN.finish_chain_inv7.I  = \FINISH_CHAIN.finish_chain6 ;
  assign \FINISH_CHAIN.finish_chain8  = \FINISH_CHAIN.finish_chain_inv8.O ;
  assign \FINISH_CHAIN.finish_chain_inv8.I  = \FINISH_CHAIN.finish_chain7 ;
  assign \FINISH_CHAIN.finish_chain9  = \FINISH_CHAIN.finish_chain_inv9.O ;
  assign \FINISH_CHAIN.finish_chain_inv9.I  = \FINISH_CHAIN.finish_chain8 ;
  assign \FINISH_CHAIN.finish_chain10  = \FINISH_CHAIN.finish_chain_inv10.O ;
  assign \FINISH_CHAIN.finish_chain_inv10.I  = \FINISH_CHAIN.finish_chain9 ;
  assign \FINISH_CHAIN.finish_chain11  = \FINISH_CHAIN.finish_chain_inv11.O ;
  assign \FINISH_CHAIN.finish_chain_inv11.I  = \FINISH_CHAIN.finish_chain10 ;
  assign \FINISH_CHAIN.finish_chain12  = \FINISH_CHAIN.finish_chain_inv12.O ;
  assign \FINISH_CHAIN.finish_chain_inv12.I  = \FINISH_CHAIN.finish_chain11 ;
  assign \FINISH_CHAIN.finish_chain13  = \FINISH_CHAIN.finish_chain_inv13.O ;
  assign \FINISH_CHAIN.finish_chain_inv13.I  = \FINISH_CHAIN.finish_chain12 ;
  assign \FINISH_CHAIN.finish_chain14  = \FINISH_CHAIN.finish_chain_inv14.O ;
  assign \FINISH_CHAIN.finish_chain_inv14.I  = \FINISH_CHAIN.finish_chain13 ;
  assign \FINISH_CHAIN.Ob  = \FINISH_CHAIN.finish_chain_inv15.O ;
  assign \FINISH_CHAIN.finish_chain_inv15.I  = \FINISH_CHAIN.finish_chain14 ;
  assign \CAP_CHAIN.cap_chain1  = \CAP_CHAIN.cap_chain_inv1.O ;
  assign \CAP_CHAIN.cap_chain_inv1.I  = \CAP_CHAIN.I ;
  assign \CAP_CHAIN.cap_chain2  = \CAP_CHAIN.cap_chain_inv2.O ;
  assign \CAP_CHAIN.cap_chain_inv2.I  = \CAP_CHAIN.cap_chain1 ;
  assign \CAP_CHAIN.cap_chain3  = \CAP_CHAIN.cap_chain_inv3.O ;
  assign \CAP_CHAIN.cap_chain_inv3.I  = \CAP_CHAIN.cap_chain2 ;
  assign \CAP_CHAIN.cap_chain4  = \CAP_CHAIN.cap_chain_inv4.O ;
  assign \CAP_CHAIN.cap_chain_inv4.I  = \CAP_CHAIN.cap_chain3 ;
  assign \CAP_CHAIN.cap_chain5  = \CAP_CHAIN.cap_chain_inv5.O ;
  assign \CAP_CHAIN.cap_chain_inv5.I  = \CAP_CHAIN.cap_chain4 ;
  assign \CAP_CHAIN.cap_chain6  = \CAP_CHAIN.cap_chain_inv6.O ;
  assign \CAP_CHAIN.cap_chain_inv6.I  = \CAP_CHAIN.cap_chain5 ;
  assign \CAP_CHAIN.cap_chain7  = \CAP_CHAIN.cap_chain_inv7.O ;
  assign \CAP_CHAIN.cap_chain_inv7.I  = \CAP_CHAIN.cap_chain6 ;
  assign \CAP_CHAIN.cap_chain8  = \CAP_CHAIN.cap_chain_inv8.O ;
  assign \CAP_CHAIN.cap_chain_inv8.I  = \CAP_CHAIN.cap_chain7 ;
  assign \CAP_CHAIN.cap_chain9  = \CAP_CHAIN.cap_chain_inv9.O ;
  assign \CAP_CHAIN.cap_chain_inv9.I  = \CAP_CHAIN.cap_chain8 ;
  assign \CAP_CHAIN.cap_chain10  = \CAP_CHAIN.cap_chain_inv10.O ;
  assign \CAP_CHAIN.cap_chain_inv10.I  = \CAP_CHAIN.cap_chain9 ;
  assign \FINISH_CHAIN.O  = \FINISH_CHAIN.finish_chain_inv16.O ;
  assign \FINISH_CHAIN.finish_chain_inv16.I  = \FINISH_CHAIN.Ob ;
  assign \CAP_CHAIN.cap_chain11  = \CAP_CHAIN.cap_chain_inv11.O ;
  assign \CAP_CHAIN.cap_chain_inv11.I  = \CAP_CHAIN.cap_chain10 ;
  assign \CAP_CHAIN.cap_chain12  = \CAP_CHAIN.cap_chain_inv12.O ;
  assign \CAP_CHAIN.cap_chain_inv12.I  = \CAP_CHAIN.cap_chain11 ;
  assign \CAP_CHAIN.cap_chain13  = \CAP_CHAIN.cap_chain_inv13.O ;
  assign \CAP_CHAIN.cap_chain_inv13.I  = \CAP_CHAIN.cap_chain12 ;
  assign \CAP_CHAIN.cap_chain14  = \CAP_CHAIN.cap_chain_inv14.O ;
  assign \CAP_CHAIN.cap_chain_inv14.I  = \CAP_CHAIN.cap_chain13 ;
  assign \CAP_CHAIN.cap_chain15  = \CAP_CHAIN.cap_chain_inv15.O ;
  assign \CAP_CHAIN.cap_chain_inv15.I  = \CAP_CHAIN.cap_chain14 ;
  assign \CAP_CHAIN.O  = \CAP_CHAIN.cap_chain_inv16.O ;
  assign \CAP_CHAIN.cap_chain_inv16.I  = \CAP_CHAIN.cap_chain15 ;
  assign \FALLING_COMP.Db_Minus  = \FALLING_COMP.INV_DM.O ;
  assign \FALLING_COMP.INV_DM.I  = \FALLING_COMP.D_Minus ;
  assign \FALLING_COMP.Db_Plus  = \FALLING_COMP.INV_DP.O ;
  assign \FALLING_COMP.INV_DP.I  = \FALLING_COMP.D_Plus ;
  assign \FALLING_COMP.Qb  = \FALLING_COMP.SR_MEM.Qb ;
  assign \FALLING_COMP.Q  = \FALLING_COMP.SR_MEM.Q ;
  assign \FALLING_COMP.SR_MEM.Rb  = \FALLING_COMP.Db_Minus ;
  assign \FALLING_COMP.SR_MEM.Sb  = \FALLING_COMP.Db_Plus ;
  assign \FALLING_COMP.Qb_b  = \FALLING_COMP.INV_Qb.O ;
  assign \FALLING_COMP.INV_Qb.I  = \FALLING_COMP.Qb ;
  assign \FALLING_COMP.Done  = \FALLING_COMP.NAND2_COMP.O ;
  assign \FALLING_COMP.NAND2_COMP.B  = \FALLING_COMP.D_Minus ;
  assign \FALLING_COMP.NAND2_COMP.A  = \FALLING_COMP.D_Plus ;
  assign \CLOCK_GEN.FinishB_Delay  = \CLOCK_GEN.INV_F.O ;
  assign \CLOCK_GEN.INV_F.I  = \CLOCK_GEN.Finish_Delay ;
  assign \CLOCK_GEN.Set_OE  = \CLOCK_GEN.NAND_DF.O ;
  assign \CLOCK_GEN.NAND_DF.B  = \CLOCK_GEN.FinishB_Delay ;
  assign \CLOCK_GEN.NAND_DF.A  = \CLOCK_GEN.Done_Falling ;
  assign \RISING_COMP.Done  = \RISING_COMP.NAND2_COMP.O ;
  assign \RISING_COMP.NAND2_COMP.B  = \RISING_COMP.D_Minus ;
  assign \RISING_COMP.NAND2_COMP.A  = \RISING_COMP.D_Plus ;
  assign \CLOCK_GEN.Reset_OE  = \CLOCK_GEN.NAND_DR.O ;
  assign \CLOCK_GEN.NAND_DR.B  = \CLOCK_GEN.Finish_Delay ;
  assign \CLOCK_GEN.NAND_DR.A  = \CLOCK_GEN.Done_Rising ;
  assign \CLOCK_GEN.OE_Falling  = \CLOCK_GEN.SR_OE.Q ;
  assign \CLOCK_GEN.SR_OE.Rb  = \CLOCK_GEN.Reset_OE ;
  assign \CLOCK_GEN.SR_OE.Sb  = \CLOCK_GEN.Set_OE ;
  assign \FALLING_COMP.Y  = \FALLING_COMP.NAND3_COMP.O ;
  assign \FALLING_COMP.NAND3_COMP.C  = \FALLING_COMP.Output_Enable ;
  assign \FALLING_COMP.NAND3_COMP.B  = \FALLING_COMP.Db_Plus ;
  assign \FALLING_COMP.NAND3_COMP.A  = \FALLING_COMP.Qb_b ;
  assign \FALLING_COMP.Q_b  = \FALLING_COMP.INV_Q.O ;
  assign \FALLING_COMP.INV_Q.I  = \FALLING_COMP.Q ;
  assign \RISING_COMP.Db_Plus  = \RISING_COMP.INV_DP.O ;
  assign \RISING_COMP.INV_DP.I  = \RISING_COMP.D_Plus ;
  assign \RISING_COMP.Db_Minus  = \RISING_COMP.INV_DM.O ;
  assign \RISING_COMP.INV_DM.I  = \RISING_COMP.D_Minus ;
  assign \RISING_COMP.Qb  = \RISING_COMP.SR_MEM.Qb ;
  assign \RISING_COMP.Q  = \RISING_COMP.SR_MEM.Q ;
  assign \RISING_COMP.SR_MEM.Rb  = \RISING_COMP.Db_Minus ;
  assign \RISING_COMP.SR_MEM.Sb  = \RISING_COMP.Db_Plus ;
  assign \RISING_COMP.Qb_b  = \RISING_COMP.INV_Qb.O ;
  assign \RISING_COMP.INV_Qb.I  = \RISING_COMP.Qb ;
  assign \CLOCK_GEN.OE_Rising  = \CLOCK_GEN.INV_OE.O ;
  assign \CLOCK_GEN.INV_OE.I  = \CLOCK_GEN.OE_Falling ;
  assign \RISING_COMP.Y  = \RISING_COMP.NAND3_COMP.O ;
  assign \RISING_COMP.NAND3_COMP.C  = \RISING_COMP.Output_Enable ;
  assign \RISING_COMP.NAND3_COMP.B  = \RISING_COMP.Db_Plus ;
  assign \RISING_COMP.NAND3_COMP.A  = \RISING_COMP.Qb_b ;
  assign \RISING_COMP.Q_b  = \RISING_COMP.INV_Q.O ;
  assign \RISING_COMP.INV_Q.I  = \RISING_COMP.Q ;
  assign \FINISH_COMP.Db_Minus  = \FINISH_COMP.INV_DM.O ;
  assign \FINISH_COMP.INV_DM.I  = \FINISH_COMP.D_Minus ;
  assign \FINISH_COMP.Db_Plus  = \FINISH_COMP.INV_DP.O ;
  assign \FINISH_COMP.INV_DP.I  = \FINISH_COMP.D_Plus ;
  assign \FINISH_COMP.Qb  = \FINISH_COMP.SR_MEM.Qb ;
  assign \FINISH_COMP.Q  = \FINISH_COMP.SR_MEM.Q ;
  assign \FINISH_COMP.SR_MEM.Rb  = \FINISH_COMP.Db_Minus ;
  assign \FINISH_COMP.SR_MEM.Sb  = \FINISH_COMP.Db_Plus ;
  assign \FINISH_COMP.Qb_b  = \FINISH_COMP.INV_Qb.O ;
  assign \FINISH_COMP.INV_Qb.I  = \FINISH_COMP.Qb ;
  assign \FINISH_COMP.Y  = \FINISH_COMP.NAND3_COMP.O ;
  assign \FINISH_COMP.NAND3_COMP.C  = \FINISH_COMP.Output_Enable ;
  assign \FINISH_COMP.NAND3_COMP.B  = \FINISH_COMP.Db_Plus ;
  assign \FINISH_COMP.NAND3_COMP.A  = \FINISH_COMP.Qb_b ;
  assign \FINISH_COMP.Done  = \FINISH_COMP.NAND2_COMP.O ;
  assign \FINISH_COMP.NAND2_COMP.B  = \FINISH_COMP.D_Minus ;
  assign \FINISH_COMP.NAND2_COMP.A  = \FINISH_COMP.D_Plus ;
  assign \FINISH_COMP.Q_b  = \FINISH_COMP.INV_Q.O ;
  assign \FINISH_COMP.INV_Q.I  = \FINISH_COMP.Q ;
  assign \CLOCK_GEN.ResetB  = \CLOCK_GEN.INV_R.O ;
  assign \CLOCK_GEN.INV_R.I  = \CLOCK_GEN.Reset ;
  assign \CLOCK_GEN.Conv_Finish  = \CLOCK_GEN.SR_Op.Q ;
  assign \CLOCK_GEN.SR_Op.Rb  = \CLOCK_GEN.ResetB ;
  assign \CLOCK_GEN.SR_Op.Sb  = \CLOCK_GEN.Finish ;
  assign \CLOCK_GEN.Sense  = \CLOCK_GEN.NOR_CLK.O ;
  assign \CLOCK_GEN.NOR_CLK.B  = \CLOCK_GEN.Conv_Finish ;
  assign \CLOCK_GEN.NOR_CLK.A  = \CLOCK_GEN.Reset ;
  assign \CLOCK_GEN.CLKb  = \CLOCK_GEN.NAND_CLK.O ;
  assign \CLOCK_GEN.NAND_CLK.B  = \CLOCK_GEN.Sense ;
  assign \CLOCK_GEN.NAND_CLK.A  = \CLOCK_GEN.OE_Falling ;
  assign \CLOCK_GEN.Next_Edge  = \CLOCK_GEN.NOT_CLK.O ;
  assign \CLOCK_GEN.NOT_CLK.I  = \CLOCK_GEN.CLKb ;
  assign \CLOCK_GEN.SR_OE.Qb  = \CLOCK_GEN.SR_OE.NANDQb.O ;
  assign \CLOCK_GEN.SR_OE.NANDQb.B  = \CLOCK_GEN.SR_OE.Q ;
  assign \CLOCK_GEN.SR_OE.NANDQb.A  = \CLOCK_GEN.SR_OE.Rb ;
  assign \CLOCK_GEN.SR_OE.Q  = \CLOCK_GEN.SR_OE.NANDQ.O ;
  assign \CLOCK_GEN.SR_OE.NANDQ.B  = \CLOCK_GEN.SR_OE.Qb ;
  assign \CLOCK_GEN.SR_OE.NANDQ.A  = \CLOCK_GEN.SR_OE.Sb ;
  assign \FINISH_COMP.SR_MEM.Qb  = \FINISH_COMP.SR_MEM.NANDQb.O ;
  assign \FINISH_COMP.SR_MEM.NANDQb.B  = \FINISH_COMP.SR_MEM.Q ;
  assign \FINISH_COMP.SR_MEM.NANDQb.A  = \FINISH_COMP.SR_MEM.Rb ;
  assign \FINISH_COMP.SR_MEM.Q  = \FINISH_COMP.SR_MEM.NANDQ.O ;
  assign \FINISH_COMP.SR_MEM.NANDQ.B  = \FINISH_COMP.SR_MEM.Qb ;
  assign \FINISH_COMP.SR_MEM.NANDQ.A  = \FINISH_COMP.SR_MEM.Sb ;
  assign \FALLING_COMP.SR_MEM.Q  = \FALLING_COMP.SR_MEM.NANDQ.O ;
  assign \FALLING_COMP.SR_MEM.NANDQ.B  = \FALLING_COMP.SR_MEM.Qb ;
  assign \FALLING_COMP.SR_MEM.NANDQ.A  = \FALLING_COMP.SR_MEM.Sb ;
  assign \FALLING_COMP.SR_MEM.Qb  = \FALLING_COMP.SR_MEM.NANDQb.O ;
  assign \FALLING_COMP.SR_MEM.NANDQb.B  = \FALLING_COMP.SR_MEM.Q ;
  assign \FALLING_COMP.SR_MEM.NANDQb.A  = \FALLING_COMP.SR_MEM.Rb ;
  assign \RISING_COMP.SR_MEM.Q  = \RISING_COMP.SR_MEM.NANDQ.O ;
  assign \RISING_COMP.SR_MEM.NANDQ.B  = \RISING_COMP.SR_MEM.Qb ;
  assign \RISING_COMP.SR_MEM.NANDQ.A  = \RISING_COMP.SR_MEM.Sb ;
  assign \RISING_COMP.SR_MEM.Qb  = \RISING_COMP.SR_MEM.NANDQb.O ;
  assign \RISING_COMP.SR_MEM.NANDQb.B  = \RISING_COMP.SR_MEM.Q ;
  assign \RISING_COMP.SR_MEM.NANDQb.A  = \RISING_COMP.SR_MEM.Rb ;
  assign \CLOCK_GEN.SR_Op.Q  = \CLOCK_GEN.SR_Op.NANDQ.O ;
  assign \CLOCK_GEN.SR_Op.NANDQ.B  = \CLOCK_GEN.SR_Op.Qb ;
  assign \CLOCK_GEN.SR_Op.NANDQ.A  = \CLOCK_GEN.SR_Op.Sb ;
  assign \CLOCK_GEN.SR_Op.Qb  = \CLOCK_GEN.SR_Op.NANDQb.O ;
  assign \CLOCK_GEN.SR_Op.NANDQb.B  = \CLOCK_GEN.SR_Op.Q ;
  assign \CLOCK_GEN.SR_Op.NANDQb.A  = \CLOCK_GEN.SR_Op.Rb ;
endmodule
